stages:
  - trigger

trigger_orders:
  stage: trigger
  trigger:
    include: apps/orders/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/orders/**/*

trigger_account:
  stage: trigger
  trigger:
    include: apps/account/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/account/**/*

trigger_notes:
  stage: trigger
  trigger:
    include: apps/notes/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/notes/**/*

trigger_request:
  stage: trigger
  trigger:
    include: apps/request/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/request/**/*

# trigger_reviews:
#   stage: trigger
#   rules:
#     - changes:
#         - apps/reviews/**/*

trigger_verify:
  stage: trigger
  trigger:
    include: apps/verify/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - apps/verify/**/*